### ISSUE TITLE
"Uncaught ReferenceError: proc is not defined" after closing the test window (test passed)

### ISSUE THREAD

**Issue by og1** [TabDigital/atom-mocha-test-runner#58]
/Users/Omar/.atom/packages/mocha-test-runner/node_modules/process-tree/index.coffee:41
Hide Stack Trace
ReferenceError: proc is not defined
    at /Users/Omar/.atom/packages/mocha-test-runner/node_modules/process-tree/index.coffee:41:47
    at ChildProcess.<anonymous> (/Users/Omar/.atom/packages/mocha-test-runner/node_modules/process-tree/index.coffee:38:4)
    at emitTwo (events.js:92:20)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

**Comment by mattdell** [comment]
Same for me.

**Comment by huwmartin** [comment]
Bump.

**Comment by rprieto** [comment]
Thanks for the report. It seems to come from `process-tree` itself, introduced in #56. [This particular line of code](https://github.com/1j01/process-tree/blob/master/index.coffee#L41) is odd, I can't see `proc` defined anywhere.

```coffee
name: info.name ? info.Name ? info.comm ? proc.cmd
```

@og1 @mattdell @huwmartin what OS do you run?

ps: also confused because the stack trace above points to CoffeeScript but this module publishes the compiled JS code. Any thoughts there?

**Comment by sergiu-paraschiv** [comment]
Stack trace is generated using the sourcemap probably.

**Comment by og1** [comment]
I have OSX 10.11.4. NodeJS 6.1.0. The previous version did not have this bug and always occurs after pressing escape to close the test window. Looks like it might have something to do with the events that are triggered when Pipe._onclose (net.js:469:12) fires.

**Comment by rad182** [comment]
+1

**Comment by sanjaypojo** [comment]
+1

**Comment by NEWeber** [comment]
I'm seeing the same issue, I'm running OSX 10.11.5 and Node 6.2.0.

**Comment by seoker** [comment]
+1

**Comment by erikkemperman** [comment]
Same here. Like @rprieto I suspect a typo in `process-tree`, have made an [issue](https://github.com/1j01/process-tree/issues/1) for it.

Just on a hunch I changed `proc.cmd` to `info.cmd` on the offending line and now things work (well, don't give a loud error).

**Comment by 1j01** [comment]
I've published `process-tree@1.0.2`, which should fix this issue.

**Comment by og1** [comment]
Sorry, problem remains the same. Tried uninstalling mocha-test-runner and reinstalling it but that did not work either. Replacing the process-tree files in the mocha-test-runner package manually did work so I guess all that is needed is a new build/update of mocha-test-runner.

**Comment by erikkemperman** [comment]
That's because `atom-mocha-test-runner` has a dependency on `"process-tree": "1.0.0"` -- no semver cleverness there. So uninstalling/reinstalling is not going to give you the fixed 1.0.2 version, until `package.json` is changed.

**Comment by og1** [comment]
True, but even adding process-tree to package.json does not help because it will add it to the node modules and leave the older version of process-tree inside mocha-test-runner.

**Comment by nguyenchr** [comment]
I will update process-tree and publish a new version :)

**Comment by og1** [comment]
Thanks Chris!

**Comment by nguyenchr** [comment]
`v0.5.1` has been published can you please update and see if it fixes your issue?

**Comment by og1** [comment]
Yes it does! Great!
